### ISSUE TITLE
MIRC - Connection OK, but no messages in chat.

### ISSUE THREAD

**Issue by suunkie** [esibun/hitbox-irc-proxy#3]
Ubuntu 14.04 with Python and other requirements installed.

If i start python hitbox-irc.py, there is no console output and i can't connect. If i press CTRL+C on console it shows following messages:

Traceback (most recent call last):
  File "hitbox-irc.py", line 484, in <module>
    IRCServer()
  File "hitbox-irc.py", line 28, in **init**
    self._HandleClients()
  File "hitbox-irc.py", line 38, in _HandleClients
    self._HandleOutgoing()
  File "hitbox-irc.py", line 44, in _HandleOutgoing
    data = self._connection.recv(4096).decode('UTF-8').split('\r\n')[:-1]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
KeyboardInterrupt

If i try to run it with python3 hitbox-irc.py then i receive this error message:

Traceback (most recent call last):
  File "hitbox-irc.py", line 1, in <module>
    import copy, json, random, requests, socket, time
ImportError: No module named 'requests'

If i now edit hitbox-irc.py 

from: data = self._connection.recv(4096).decode('UTF-8').split('\r\n')[:-1]
to: data = self._connection.recv(4096).decode('UTF-8').split('\r\n')[:-1]

i could connect to proxy, but dont see any chat messages in MIRC which are send by users in the chat. But i see following error messages on console:

Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/ws4py/websocket.py", line 427, in run
    if not self.once():
  File "/usr/lib/python2.7/dist-packages/ws4py/websocket.py", line 305, in once
    if not self.process(b):
  File "/usr/lib/python2.7/dist-packages/ws4py/websocket.py", line 377, in process
    self.received_message(s.message)
  File "hitbox-irc.py", line 316, in received_message
    self._irc.HitboxMessage(str(message))
  File "hitbox-irc.py", line 178, in HitboxMessage
    self._hitboxChat[channel].names(channel)
KeyError: u'ashk0retv'

In addition, if i write in MIRC i don't see any output in hitbox chat, but i can see on console that the proxy received the messages i typed in MIRC.

**Comment by esibun** [comment]
So since I actually have a bit of time to work on this, now that I'm done with the majority of my schoolwork, here's the deal:

There seems to be some interest in this project, so I've decided to come back to it and try to fix it up.

I'm not really happy with how dense the code looks at the minute, so I've started rewriting the code using the asyncio library.  Hopefully, that will make it a lot easier to make updates to the code since I won't have to search around for what does what.  It will also mean that it will be easier to support every possible command that you can do with the Hitbox API.

I'll make the adjustment that you noted in the old code.  The second error that you're getting is because you don't have the required module 'requests' installed for python3.  You can install this by running either the command `easy_install requests` or `pip install requests` (for Ubuntu, the python3 equivalents are `easy_install3` and `pip3` I believe).  Not really sure what the third message is, but once I get the rewrite done I'm going to do more complete testing on all of the major clients (mIRC, HexChat, etc.)

I could probably make the documentation much better by including more in-depth instructions on all of this as well.

**Comment by CGLeBel** [comment]
Thank you for your hard work, Im sure a lot of channel could be created
with your code, Ill keep you updated with the development of any Hitbox
Plays channels for feedback purposes.

Regards,
TPPR

**Comment by suunkie** [comment]
Thanks for your hard work and for coming back to your project. :)

**Comment by esibun** [comment]
I've merged the rewrite branch.  After testing with mIRC, connections and text appear to be working on my end.  User list is still broken because I need to implement it - see #4.
